version: '3.6'

services:
  db1:
    container_name: db1
    restart: always
    image: "postgres:10.1-alpine"
    volumes:
      - ./db/postgres/log:/var/log/postgresql
      - ./db/postgres/backup:/backup
      - ./db/postgres/conf:/etc/postgresql/
    ports:
      - 5432:5432
    expose:
      - "5432"

  fe:
    container_name: fe
    restart: always
    build: './fe'
    command: 'python ./app.py'
    volumes:
      - ./fe:/code
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db1
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db1

  be-tests:
    container_name: be-tests
    build: './be-tests'
    command: ./run.sh
    volumes:
      - ./be-tests:/usr/src/app
    ports:
      - 3001:3001
    expose:
      - 8000
    links:
      - fe
    depends_on:
      - db1
      - fe

  selenium:
    container_name: selenium
    build: './fe-tests'
    command: 'behave -f allure_behave.formatter:AllureFormatter -o . ./features'
    command: 'SimpleHTTPServer 3002 --bind 127.0.0.1'
    volumes:
      - ./fe-tests:/code
    ports:
      - 4444:4444
      - 3002:3002
    depends_on:
      - fe
      - db1
