version: '3.6'

services:
  db1:
    container_name: db1
    restart: always
    image: "postgres:10.1-alpine"
    volumes:
      - ./db/postgres/log:/var/log/postgresql
      - ./db/postgres/backup:/backup
      - ./db/postgres/conf:/etc/postgresql/
    ports:
      - 5432:5432
    expose:
      - "5432"

  flask:
    container_name: flask
    restart: always
    build: './flask'
    command: 'python ./app.py'
    volumes:
      - ./flask:/code
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db1
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db1

  api-tests:
    container_name: api-tests
    build: './api-tests'
    command: ./run.sh
    volumes:
      - ./api-tests:/usr/src/app
    ports:
      - 3001:3001
    expose:
      - 8000
    links:
      - flask
    depends_on:
      - db1
      - flask

  selenium:
    container_name: selenium
    build: './ui-tests'
    command: 'behave -f allure_behave.formatter:AllureFormatter -o . ./features'
    command: 'SimpleHTTPServer 3002 --bind 127.0.0.1'
    volumes:
      - ./ui-tests:/code
    ports:
      - 4444:4444
      - 3002:3002
    depends_on:
      - flask
      - db1
